apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicalrepresentativeschedule-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicalRepScheduleService
  template:
    metadata:
      labels:
        app: MedicalRepScheduleService
    spec:
      containers:
      - name: medicalrepresentativeschedule
        image: medicinesupplycr.azurecr.io/medicalrepresentativeschedule:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: medicalrepresentativeschedule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicalRepScheduleService
